GET http://localhost:5000/users
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJuYW1lIjoicmFpaGFuIiwiZW1haWwiOiJyYWloYW5AZ21haWwuY29tIiwiaWF0IjoxNjczNzAyOTI5LCJleHAiOjE2NzM3MDI5NDR9.KByUY22HGjLC2lgN4ymvX_QzDUKJdf7G4I5d0QL8-nM


###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name": "ihan",
    "email": "ihan@gmail.com",
    "password": "12345678",
    "confpassword": "12345678"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "raihan@gmail.com",
    "password" : "12345678"
}

###
GET  http://localhost:5000/token

###
DELETE http://localhost:5000/logout