GET http://localhost:5000/users

###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name": "fauzan",
    "email": "fauzan@gmail.com",
    "password": "12345678",
    "confpassword": "12345678"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "fauzan@gmail.com",
    "password" : "12345678"
}